builds:
  - main: main.go
    binary: 2to3
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
archives:
  - id: archive
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - plugin.yaml
      - completion.yaml
      - scripts/install_plugin.sh
checksum:
  name_template: 'checksums.txt'
