version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x scripts/tag.sh
            shellcheck -x scripts/install_plugin.sh
  untagged-build:
    docker:
      - image: circleci/golang:1.16
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: /go/src/github.com/helm/helm-2to3
    steps:
      - checkout
      - run: make build
  tagged-build:
    docker:
      - image: circleci/golang:1.16
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    working_directory: /go/src/github.com/helm/helm-2to3
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - untagged-build
  tagged-build:
    jobs:
      - tagged-build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
